document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="controls.css">');
const TARGET='2026-09-17T19:00';
const CITIES=[['Seattle',47.6062,-122.3321],['Portland',45.5152,-122.6784],['San Francisco',37.7749,-122.4194],['Los Angeles',34.0522,-118.2437],['San Diego',32.7157,-117.1611],['Las Vegas',36.1699,-115.1398],['Phoenix',33.4484,-112.0740],['Salt Lake City',40.7608,-111.8910],['Denver',39.7392,-104.9903],['Albuquerque',35.0844,-106.6504],['Boise',43.6150,-116.2023],['Billings',45.7833,-108.5007],['Fargo',46.8772,-96.7898],['Minneapolis',44.9778,-93.2650],['Omaha',41.2565,-95.9345],['Kansas City',39.0997,-94.5786],['Oklahoma City',35.4676,-97.5164],['Dallas',32.7767,-96.7970],['Austin',30.2672,-97.7431],['Houston',29.7604,-95.3698],['New Orleans',29.9511,-90.0715],['Memphis',35.1495,-90.0490],['St. Louis',38.6270,-90.1994],['Chicago',41.8781,-87.6298],['Detroit',42.3314,-83.0458],['Indianapolis',39.7684,-86.1581],['Nashville',36.1627,-86.7816],['Atlanta',33.7490,-84.3880],['Miami',25.7617,-80.1918],['Tampa',27.9506,-82.4572],['Charlotte',35.2271,-80.8431],['Raleigh',35.7796,-78.6382],['Charlottesville',38.0293,-78.4767],['Washington, DC',38.9072,-77.0369],['Baltimore',39.2904,-76.6122],['Philadelphia',39.9526,-75.1652],['New York',40.7128,-74.0060],['Boston',42.3601,-71.0589],['Pittsburgh',40.4406,-79.9959],['Cleveland',41.4993,-81.6944]];
const COLORS=['#C79A4A','#B85C38','#3D7182','#667761'];
// Standardized teaching logistic model trained on 2026 U.S. city-hour observations.
const LOGISTIC={mean:[67.89036,52.09071,6.66046,49.26286],scale:[20.21418,24.83057,3.50898,41.20323],coef:[0.66983,1.34314,0.21971,0.86157],intercept:-1.0368230648012693};
const state={forecasts:[],payloads:[],clusters:[],groups:[],selected:'Charlottesville',map:null,markers:[]};
const cfg={responsive:true,displaylogo:false,toImageButtonOptions:{format:'png',height:900,width:1600,scale:2}};
const sigmoid=z=>1/(1+Math.exp(-z));
function logisticProbability(x){let z=LOGISTIC.intercept;for(let i=0;i<4;i++)z+=LOGISTIC.coef[i]*(x[i]-LOGISTIC.mean[i])/LOGISTIC.scale[i];return sigmoid(z)}
function forecastURL(cities,past=14){return `https://api.open-meteo.com/v1/forecast?latitude=${cities.map(c=>c[1]).join(',')}&longitude=${cities.map(c=>c[2]).join(',')}&hourly=temperature_2m,relative_humidity_2m,precipitation_probability,cloud_cover,wind_speed_10m&temperature_unit=fahrenheit&wind_speed_unit=mph&precipitation_unit=inch&timezone=auto&past_days=${past}&forecast_days=7`}
function atTarget(city,payload){const i=payload.hourly.time.indexOf(TARGET);if(i<0)throw new Error(`Target hour unavailable for ${city[0]}`);const h=payload.hourly,x=[h.temperature_2m[i],h.relative_humidity_2m[i],h.wind_speed_10m[i],h.cloud_cover[i]];return{name:city[0],lat:city[1],lon:city[2],timezone:payload.timezone,temp:x[0],humidity:x[1],rainAPI:h.precipitation_probability[i],cloud:x[3],wind:x[2],logistic:logisticProbability(x)}}
function standardize(rows,keys){const means=keys.map(k=>rows.reduce((s,r)=>s+r[k],0)/rows.length),sds=keys.map((k,j)=>Math.sqrt(rows.reduce((s,r)=>s+(r[k]-means[j])**2,0)/rows.length)||1);return rows.map(r=>keys.map((k,j)=>(r[k]-means[j])/sds[j]))}
function kmeans(X,k=4){let centers=[0,10,20,30].map(i=>X[i%X.length].slice()),labels=[];for(let n=0;n<30;n++){const distances=X.map(x=>centers.map(c=>c.reduce((s,v,j)=>s+(x[j]-v)**2,0)));labels=distances.map(d=>d.indexOf(Math.min(...d)));centers=centers.map((old,j)=>{const g=X.filter((x,i)=>labels[i]===j);return g.length?old.map((_,p)=>g.reduce((s,x)=>s+x[p],0)/g.length):old})}return labels}
function labelClusters(rows,labels){const groups=[0,1,2,3].map(k=>{const g=rows.filter((_,i)=>labels[i]===k),avg=v=>g.reduce((s,r)=>s+r[v],0)/g.length;return{k,temp:avg('temp'),humidity:avg('humidity'),rain:avg('rainAPI'),cloud:avg('cloud'),wind:avg('wind'),n:g.length}});const hot=Math.max(...groups.map(g=>g.temp)),wet=Math.max(...groups.map(g=>g.rain)),cool=Math.min(...groups.map(g=>g.temp));groups.forEach(g=>g.label=g.rain===wet?'Rain-prone':g.temp===hot?'Warm evening':g.temp===cool?'Cool evening':'Mild transition');return groups}
function setupMap(){state.map=L.map('map',{zoomControl:true}).setView([38.3,-97],4);L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:18,attribution:'Tiles © Esri — Esri, Maxar, Earthstar Geographics'}).addTo(state.map);L.tileLayer('https://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}',{maxZoom:18,attribution:'Labels © Esri'}).addTo(state.map)}
function renderMap(groups){state.markers.forEach(m=>m.remove());state.markers=[];state.forecasts.forEach((r,i)=>{const g=groups[state.clusters[i]],m=L.circleMarker([r.lat,r.lon],{radius:r.name===state.selected?12:8,color:'#fff',weight:2,fillColor:COLORS[g.k],fillOpacity:.92}).addTo(state.map).bindTooltip(`<b>${r.name}</b><br>${g.label}<br>${r.temp.toFixed(1)}°F · ${r.rainAPI}% provider forecast rain<br>${(100*r.logistic).toFixed(0)}% logistic probability`);m.on('click',()=>{document.getElementById('citySelect').value=r.name;state.selected=r.name;renderSelected(groups)});state.markers.push(m)});document.getElementById('clusterLegend').innerHTML=groups.map(g=>`<div class="cluster-key" style="--cluster:${COLORS[g.k]}"><b>${g.label}</b>${g.n} cities · ${g.temp.toFixed(0)}°F · ${g.rain.toFixed(0)}% forecast rain</div>`).join('')}
function solve(A,b){const n=b.length,M=A.map((r,i)=>[...r,b[i]]);for(let i=0;i<n;i++){let p=i;for(let j=i+1;j<n;j++)if(Math.abs(M[j][i])>Math.abs(M[p][i]))p=j;[M[i],M[p]]=[M[p],M[i]];let d=M[i][i]||1e-9;for(let j=i;j<=n;j++)M[i][j]/=d;for(let k=0;k<n;k++)if(k!==i){let f=M[k][i];for(let j=i;j<=n;j++)M[k][j]-=f*M[i][j]}}return M.map(r=>r[n])}
function arFit(y,p=5){let X=[],t=[];for(let i=p;i<y.length;i++){X.push([1,...Array.from({length:p},(_,j)=>y[i-j-1])]);t.push(y[i])}const q=p+1,A=Array.from({length:q},()=>Array(q).fill(0)),b=Array(q).fill(0);X.forEach((r,i)=>{for(let a=0;a<q;a++){b[a]+=r[a]*t[i];for(let c=0;c<q;c++)A[a][c]+=r[a]*r[c]}});return solve(A,b)}
function bestAlpha(y){let best={a:.2,sse:Infinity};for(let a=.05;a<1;a+=.05){let l=y[0],s=0;for(let i=1;i<y.length;i++){s+=(y[i]-l)**2;l=a*y[i]+(1-a)*l}if(s<best.sse)best={a,sse:s}}return best.a}
function modelSeries(payload){const h=payload.hourly,localNow=new Date(Date.now()+payload.utc_offset_seconds*1000).toISOString().slice(0,13)+':00',cut=h.time.findLastIndex(t=>t<=localNow),target=h.time.indexOf(TARGET),begin=Math.max(5,cut-24*14),y=h.temperature_2m.slice(begin,cut+1).filter(Number.isFinite),steps=target-cut;if(steps<1)throw new Error('Target time has passed or is unavailable.');const naive=Array(steps).fill(y.at(-1)),coef=arFit(y,5),hist=y.slice(),ar=[];for(let s=0;s<steps;s++){let v=coef[0];for(let j=0;j<5;j++)v+=coef[j+1]*hist[hist.length-j-1];ar.push(v);hist.push(v)}const alpha=bestAlpha(y),level=y.reduce((l,v,i)=>i?alpha*v+(1-alpha)*l:v,y[0]),ses=Array(steps).fill(level);return{times:h.time.slice(cut+1,target+1),actualTimes:h.time.slice(Math.max(0,cut-48),cut+1),actual:h.temperature_2m.slice(Math.max(0,cut-48),cut+1),naive,ar,ses,alpha,targetForecast:h.temperature_2m[target]}}
function layout(title,ytitle){return{title:{text:title,x:.03},font:{family:'Inter,system-ui',color:'#2B2521'},paper_bgcolor:'#fff',plot_bgcolor:'#fff',margin:{l:60,r:25,t:78,b:55},xaxis:{gridcolor:'#eee4d8'},yaxis:{title:ytitle,gridcolor:'#eee4d8'},legend:{x:.99,y:.99,xanchor:'right',yanchor:'top',bgcolor:'rgba(255,255,255,.88)',bordercolor:'#ded4c7',borderwidth:1}}}
function renderSelected(groups){const r=state.forecasts.find(x=>x.name===state.selected),g=groups[state.clusters[state.forecasts.indexOf(r)]];document.getElementById('snapshot').innerHTML=`<div class="metric"><strong>${r.temp.toFixed(1)}°F</strong><span>forecast temperature</span></div><div class="metric"><strong>${r.humidity}%</strong><span>relative humidity</span></div><div class="metric"><strong>${r.wind.toFixed(1)} mph</strong><span>wind speed</span></div><div class="metric"><strong>${r.cloud}%</strong><span>cloud cover</span></div><div class="metric"><strong>${g.label}</strong><span>national weather cluster</span></div>`;const p=100*r.logistic;document.getElementById('rainGaugeValue').textContent=`${p.toFixed(0)}%`;document.getElementById('rainInterpretation').textContent=`The teaching logistic model assigns ${state.selected} a ${p.toFixed(1)}% probability of measurable rain at 7 PM.`;document.getElementById('rainDrivers').innerHTML=`<div class="driver"><b>${r.temp.toFixed(1)}°F</b>temperature</div><div class="driver"><b>${r.humidity}%</b>humidity</div><div class="driver"><b>${r.wind.toFixed(1)} mph</b>wind</div><div class="driver"><b>${r.cloud}%</b>cloud cover</div>`;Plotly.react('rainGauge',[{type:'indicator',mode:'gauge+number',value:p,number:{suffix:'%'},gauge:{axis:{range:[0,100]},bar:{color:'#B85C38'},steps:[{range:[0,30],color:'#e5eadf'},{range:[30,65],color:'#f3e2c4'},{range:[65,100],color:'#e8cfc3'}]}}],{margin:{l:35,r:35,t:30,b:10},paper_bgcolor:'#fff'},cfg);document.getElementById('selectedClusterText').innerHTML=`<b>${state.selected}</b> belongs to <b>${g.label}</b>. Its cluster center is ${g.temp.toFixed(1)}°F, ${g.humidity.toFixed(0)}% humidity, ${g.wind.toFixed(1)} mph wind, and ${g.rain.toFixed(0)}% forecast rain.`;renderClusterChart(groups);loadCitySeries(r.name)}
function renderClusterChart(groups){const traces=groups.map(g=>{const rows=state.forecasts.filter((_,i)=>state.clusters[i]===g.k);return{x:rows.map(r=>r.temp),y:rows.map(r=>r.humidity),text:rows.map(r=>r.name),customdata:rows.map(r=>[r.rainAPI,r.wind]),type:'scatter',mode:'markers+text',textposition:'top center',name:g.label,marker:{size:11,color:COLORS[g.k]},hovertemplate:'<b>%{text}</b><br>%{x:.1f}°F · %{y}% humidity<br>%{customdata[0]}% forecast rain<extra></extra>'}});Plotly.react('clusterChart',traces,layout('U.S. city clusters at 7 PM','Relative humidity (%)'),cfg)}
async function loadCitySeries(name){try{const city=CITIES.find(c=>c[0]===name),data=await fetch(forecastURL([city],14)).then(r=>r.json()),p=Array.isArray(data)?data[0]:data,s=modelSeries(p);document.getElementById('modelScores').innerHTML=`<div class="score"><b>Naive ${s.naive.at(-1).toFixed(1)}°F</b>latest value repeated</div><div class="score"><b>AR(5) ${s.ar.at(-1).toFixed(1)}°F</b>five recursive lags</div><div class="score"><b>Exp. smoothing ${s.ses.at(-1).toFixed(1)}°F</b>α = ${s.alpha.toFixed(2)}</div><div class="score"><b>Open-Meteo ${s.targetForecast.toFixed(1)}°F</b>reference forecast</div>`;Plotly.react('temperatureChart',[{x:s.actualTimes,y:s.actual,type:'scatter',mode:'lines',name:'Recent hourly temperature',line:{color:'#152A3A',width:3}},{x:s.times,y:s.naive,type:'scatter',mode:'lines',name:'Naive',line:{color:'#C79A4A',dash:'dash'}},{x:s.times,y:s.ar,type:'scatter',mode:'lines',name:'AR(5)',line:{color:'#B85C38',width:2.5}},{x:s.times,y:s.ses,type:'scatter',mode:'lines',name:'Exponential smoothing',line:{color:'#667761',dash:'dot'}}],layout(`Forecast path to Sept. 17 at 7 PM · ${name}`,'Temperature (°F)'),cfg)}catch(e){document.getElementById('modelScores').innerHTML=`<div class="score"><b>Unavailable</b>${e.message}</div>`}}
function updateModels(){state.clusters=kmeans(standardize(state.forecasts,['temp','humidity','wind','cloud','rainAPI']),4);state.groups=labelClusters(state.forecasts,state.clusters);renderMap(state.groups);renderSelected(state.groups);document.getElementById('previewButton').disabled=false;document.getElementById('updatedAt').textContent=`Loaded ${new Date().toLocaleString()}`}
async function fetchNational(){const button=document.getElementById('fetchButton'),status=document.getElementById('status');try{button.disabled=true;button.textContent='Fetching…';status.textContent='Retrieving live forecast data for U.S. cities…';status.className='status';let data=await fetch(forecastURL(CITIES,0)).then(r=>{if(!r.ok)throw new Error(`Weather service returned ${r.status}`);return r.json()});if(!Array.isArray(data))data=[data];state.payloads=data;state.forecasts=CITIES.map((c,i)=>atTarget(c,data[i]));updateModels();status.textContent='Live forecast loaded. Preview the rows, add another city, or explore the models.';status.className='status ready'}catch(e){console.error(e);status.textContent=`Could not load live weather data: ${e.message}`;status.className='status error'}finally{button.disabled=false;button.textContent='Fetch latest U.S. data'}}
function showPreview(){const i=CITIES.findIndex(c=>c[0]===state.selected),payload=state.payloads[i];if(!payload)return;const h=payload.hourly,start=h.time.indexOf('2026-09-17T17:00'),rows=[];for(let j=start;j<=start+4;j++)rows.push(`<tr><td>${h.time[j].replace('T',' ')}</td><td>${h.temperature_2m[j].toFixed(1)}</td><td>${h.relative_humidity_2m[j]}%</td><td>${h.precipitation_probability[j]}%</td><td>${h.cloud_cover[j]}%</td><td>${h.wind_speed_10m[j].toFixed(1)}</td></tr>`);document.getElementById('previewTitle').textContent=`${state.selected}: rows around 7 PM`;document.getElementById('previewRows').innerHTML=rows.join('');document.getElementById('dataPreview').hidden=false}
async function addCity(event){event.preventDefault();const input=document.getElementById('cityInput'),query=input.value.trim(),status=document.getElementById('status');if(!query)return;try{status.textContent=`Finding ${query}…`;const geo=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(query)}&count=5&language=en&format=json&countryCode=US`).then(r=>r.json());if(!geo.results?.length)throw new Error('No matching U.S. city found');const x=geo.results[0],name=x.admin1?`${x.name}, ${x.admin1}`:x.name,city=[name,x.latitude,x.longitude];let index=CITIES.findIndex(c=>c[0]===name);if(index<0){CITIES.push(city);const p=await fetch(forecastURL([city],0)).then(r=>r.json()),payload=Array.isArray(p)?p[0]:p;state.payloads.push(payload);state.forecasts.push(atTarget(city,payload));index=CITIES.length-1;document.getElementById('citySelect').add(new Option(name,name))}state.selected=name;document.getElementById('citySelect').value=name;updateModels();state.map.setView([city[1],city[2]],7);input.value='';status.textContent=`Added ${name} and refreshed the clusters.`;status.className='status ready'}catch(e){status.textContent=`Could not add city: ${e.message}`;status.className='status error'}}
function init(){setupMap();const select=document.getElementById('citySelect');CITIES.forEach(c=>select.add(new Option(c[0],c[0])));select.value=state.selected;select.addEventListener('change',()=>{state.selected=select.value;if(state.forecasts.length)renderSelected(state.groups)});document.getElementById('fetchButton').addEventListener('click',fetchNational);document.getElementById('cityForm').addEventListener('submit',addCity);document.getElementById('previewButton').addEventListener('click',showPreview);document.getElementById('closePreview').addEventListener('click',()=>document.getElementById('dataPreview').hidden=true)}
document.getElementById('cityForm').addEventListener('submit',async e=>{if(!state.forecasts.length){e.preventDefault();e.stopImmediatePropagation();await fetchNational();document.getElementById('cityForm').requestSubmit()}},true);
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.model-card').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(`${b.dataset.tab}Panel`).classList.add('active');setTimeout(()=>window.dispatchEvent(new Event('resize')),30)}));init();
